### ISSUE TITLE
Add Dependencies

### ISSUE THREAD

**Issue by Khanx** [Dorky106/CSModManager#1]
There are mods that may depend on others to work, such as the _BetterTrees_ or _Rise of the New Colonies_ that needs _NewColonyAPI_ .

The suggestion is to add a new tag to: mods.xml

Tag: DependsOn

Where you include the mods needed to make work your mod.

### Example

```xml
<Mod>
	<ModFolder>JackPS9\BetterTrees</ModFolder>
	<ReleaseURL>https://api.github.com/repos/Dorky106/BetterTrees/releases</ReleaseURL>
	<ConfigLocation></ConfigLocation>
	<ConfigFile></ConfigFile>
	<Dependencies>
		<DependsOn>
			<ModFolder>JackPS9\NewColonyAPI</ModFolder>
			<ReleaseURL>https://api.github.com/repos/Dorky106/NewColonyAPI/releases</ReleaseURL>
		</DependsOn>
		<DependsOn>
			<ModFolder>OTHER_MOD</ModFolder>
			<ReleaseURL>https://api.github.com/repos/OWNER/OTHER_MOD/releases</ReleaseURL>
		</DependsOn>
		</Dependencies>
	</Mod>
```

**Comment by Dorky106** [comment]
Will do, but not going to add more URL calls to the program, just going to use name instead, along with the creator name.  Doing this will lower the chance of getting a 404 when loading up the mods, and still be able to get the correct mod a mod depends on.

So if a mod depended on Settlers, the name would be under how the mod manager has it.
EX: Pandaros.Settlers

**Comment by Dorky106** [comment]
Mod dependencies have been added
